server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: telegram-microservice
  jmx:
    enabled: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic:
  request: request-to-exercises
  response: response-from-exercises

telegram:
  bot:
    botName:
    botToken: