server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: telegram-microservice
  jmx:
    enabled: false
  aop:
    proxy-target-class: true

kafka:
  topic:
    messages: messages-to-exercises
    actions: actions-from-exercises
    main-menu-commands: main-menu-commands
    media: media-from-exercises
  group.id:
    main-menu-commands: main-menu-command-group
    actions: exercise_bot_group
    media: media-group


telegram:
  bot:
    botName:
    botToken: