server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: telegram-microservice
  jmx:
    enabled: false

kafka.topic:
  messages: messages-to-exercises
  actions: actions-from-exercises
  main-menu-commands: main-menu-commands

telegram:
  bot:
    botName:
    botToken: