version: '3.8'

services:
  exercises:
    build: ./exercises/exercise-microservice
    ports:
      - "8080:8080"
    container_name: exercises
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/tgbot
      spring.datasource.username: ${POSTGRES_USER}
      spring.datasource.password: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  telegram:
    build: ./telegram
    volumes:
      - ./resources:/app/resources
    ports:
      - '8081:8081'
    restart: unless-stopped
    environment:
      telegram.bot.botName: ${TELEGRAM_BOT_NAME}
      telegram.bot.botToken: ${TELEGRAM_BOT_TOKEN}
    container_name: telegram
    depends_on:
      - exercises

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # имя БД
      POSTGRES_DB: tgbot
      POSTGRES_SCHEMA: public
      STOP_ON_MIGRATION_FAILURE: "false"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    external: false
