INSERT INTO exercise (description, image_url, muscle_group, name, video_url)
VALUES
    ('Разгибания на трицепс в блоке', NULL, 'ARMS', 'Triceps extension', NULL),
    ('Тяга верхнего блока', NULL, 'BACK', 'Upper block pulls', NULL),
    ('Тяга горизонтального блока', NULL, 'BACK', 'Horizontal block pulls', NULL),
    ('Тяга гантелей в наклоне', NULL, 'BACK', 'Bent-over dumbbell row', NULL),
    ('Подъемы на бицепс со штангой', NULL, 'ARMS', 'Barbell bicep curls', NULL),
    ('Подъемы на бицепс с гантелями', NULL, 'ARMS', 'Dumbbell bicep curls', NULL),
    ('Французский жим с гантелями', NULL, 'ARMS', 'Dumbbell French press', NULL),
    ('Приседания со штангой', NULL, 'LEGS', 'Barbell squats', NULL),
    ('Жим ногами', NULL, 'LEGS', 'Leg press', NULL),
    ('Выпады с гантелями', NULL, 'LEGS', 'Dumbbell lunges', NULL),
    ('Разгибания ног в тренажере', NULL, 'LEGS', 'Leg extensions on the machine', NULL),
    ('Сгибания ног в тренажере', NULL, 'LEGS', 'Leg curls on the machine', NULL),
    ('Жим гантелей сидя', NULL, 'SHOULDERS', 'Dumbbell press', NULL),
    ('Подъемы гантелей в стороны', NULL, 'SHOULDERS', 'Lateral dumbbell raises', NULL),
    ('Скручивания на пресс', NULL, 'CORE', 'Ab crunches', NULL),
    ('Разведение гантелей в наклоне', NULL, 'SHOULDERS', 'Bent-over dumbbell flyes', 'https://youtu.be/ttvfGg9d76c?si=_xc3EXWeZ7G65H4h'),
    ('Жим Арнольда', NULL, 'SHOULDERS', 'Arnold press', NULL),
    ('Армейский жим', NULL, 'SHOULDERS', 'Military press', NULL),
    ('Подъемы ног в висе', NULL, 'CORE', 'Hanging leg raises', NULL),
    ('Жим гантелей', NULL, 'CHEST', 'Dumbbell bench press', NULL),
    ('Разведение гантелей', NULL, 'CHEST', 'Dumbbell flyes', NULL),
    ('Жим штанги лежа', NULL, 'CHEST', 'Barbell bench press', NULL);
