spring.main:
  banner-mode: 'off'
logging.level:
  root: INFO

spring:
  profiles:
    active: local
  application.name: exercises
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    schemas: public
    validateMigrationNaming: true
  kafka:
    bootstrap-servers: ${kafka.server}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: server.exercise.results
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  cache:
    type: redis
    redis:
      time-to-live: 100000
  data:
    redis:
      port: 6379
      repositories:
        enabled: false

kafka.topic:
  request: request-to-exercises
  response: response-from-exercises