spring.main:
  banner-mode: 'off'
logging.level:
  root: INFO

spring:
  application.name: exercises
  datasource:
    url: jdbc:postgresql://localhost:5432/tgbot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    schemas: public
    validateMigrationNaming: true