name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Check if new image exists for exercises
        id: check_exercises_image
        run: |
          if docker pull ${{ secrets.DOCKER_USERNAME }}/exercises:${{ github.sha }}; then
            echo "image_exists=true" >> $GITHUB_ENV
          else
            echo "image_exists=false" >> $GITHUB_ENV
          fi

      - name: Check if new image exists for telegram
        id: check_telegram_image
        run: |
          if docker pull ${{ secrets.DOCKER_USERNAME }}/telegram:${{ github.sha }}; then
            echo "image_exists=true" >> $GITHUB_ENV
          else
            echo "image_exists=false" >> $GITHUB_ENV
          fi

      - name: Deploy Services
        if: env.image_exists == 'true'
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/exercises:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/telegram:latest
          docker-compose down
          docker-compose up -d
