name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy Exercises Service
        if: ${{ github.event.workflow_run.outputs.EXERCISES_IMAGE_UPDATED == 'true' }}
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/exercises:latest
          docker-compose up -d exercises

      - name: Deploy Telegram Service
        if: ${{ github.event.workflow_run.outputs.TELEGRAM_IMAGE_UPDATED == 'true' }}
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/telegram:latest
          docker-compose up -d telegram
