name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests=true

      - name: Run Tests
        run: mvn test
        continue-on-error: true

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t kvansipto_exercises .
        
      - name: Push to DockerHub
        run: docker push kvansipto1/kvansipto_exercises:latest
        
      
