name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests=true

      - name: Run tests
        run: mvn test
        continue-on-error: true

  docker-publish:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/exercises:latest
          context: ./exercises/exercise-microservice
          file: ./exercises/exercise-microservice/Dockerfile

      - name: Build and push Telegram Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/telegram:latest
          context: ./telegram
          file: ./telegram/Dockerfile

      - name: Set output for successful publish
        id: set-output
        run: echo "::set-output name=docker_published::true"

outputs:
  docker_published: ${{ steps.set-output.outputs.docker_published }}
