name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Сборка проекта без тестов
      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests=true

      # Запуск тестов отдельно, чтобы они не блокировали сборку
      - name: Run Tests
        run: mvn test
        continue-on-error: true

      # Если сборка успешна, деплой на EC2
      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/app
          docker-compose down
          docker-compose up -d --build
          EOF
